id: componentservice_to_observable_feature_association
schema_generating: true
display_name: componentservice to observable feature association
document_category: componentservice to observable feature association
weight: 20
fields:
- id: id
  description: A unique identifier for an entity. Must be either a CURIE shorthand
    for a URI or a complete URI
  display_name: id
- id: iri
  description: An IRI for an entity. This is determined by the id using expansion
    rules.
  display_name: iri
- id: name
  description: A human-readable name for an attribute or entity.
  display_name: name
- id: description
  description: a human-readable description of an entity
  display_name: description
- id: source
  description: a lightweight analog to the association class 'has provider' slot,
    which is the string name, or the authoritative (i.e. database) namespace, designating
    the origin of the entity to which the slot belongs.
  display_name: source
- id: provided_by
  description: connects an association to the agent (service, organization or group)
    that provided it
  display_name: provided by
  cardinality: multi
- id: has_attribute
  description: connects any entity to an attribute
  display_name: has attribute
  cardinality: multi
- id: predicate
  description: A high-level grouping for the relationship type. AKA minimal predicate.
    This is analogous to category for nodes.
  display_name: predicate
- id: object
  description: connects an association to the object of the association. For example,
    in a componentservice-to-observability association, the componentservice is subject
    and observability is object.
  display_name: object
- id: relation
  description: The relation which describes an association between a subject and an
    object in a more granular manner. Usually this is a term from Relation Ontology,
    but it can be any edge CURIE.
  display_name: relation
- id: negated
  description: if set to true, then the association is negated i.e. is not true
  display_name: negated
- id: qualifiers
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: qualifiers
  cardinality: multi
- id: publications
  description: connects an association to publications supporting the association
  display_name: publications
  cardinality: multi
- id: type
  description: rdf:type of csolink:Association should be fixed at rdf:Statement
  display_name: association_type
- id: category
  display_name: association_category
  cardinality: multi
- id: subject
  description: componentservice in which variation is correlated with the observable
    feature
  display_name: componentservice to observable feature association_subject
- id: frequency_qualifier
  description: a qualifier used in a observable association to state how frequent
    the observability is observed in the subject
  display_name: frequency qualifier
- id: severity_qualifier
  description: a qualifier used in a observable association to state how severe the
    observability is in the subject
  display_name: severity qualifier
- id: onset_qualifier
  description: a qualifier used in a observable association to state when the observability
    appears is in the subject
  display_name: onset qualifier
- id: architectural_style_qualifier
  description: a qualifier used in a observable association to state whether the association
    is specific to a particular architectural style.
  display_name: architectural style qualifier
