id: service_background_exposure
schema_generating: true
description: A service background exposure is where an individual's specific service
  background of serviceunits, sequence variants or other pre-existing service conditions
  constitute a kind of 'exposure' to the system, leading to or influencing an outcome.
display_name: service background exposure
document_category: service background exposure
weight: 20
fields:
- id: id
  description: A unique identifier for an entity. Must be either a CURIE shorthand
    for a URI or a complete URI
  display_name: id
- id: iri
  description: An IRI for an entity. This is determined by the id using expansion
    rules.
  display_name: iri
- id: type
  display_name: type
- id: name
  description: A human-readable name for an attribute or entity.
  display_name: name
- id: description
  description: a human-readable description of an entity
  display_name: description
- id: source
  description: a lightweight analog to the association class 'has provider' slot,
    which is the string name, or the authoritative (i.e. database) namespace, designating
    the origin of the entity to which the slot belongs.
  display_name: source
- id: provided_by
  description: connects an association to the agent (service, organization or group)
    that provided it
  display_name: provided by
  cardinality: multi
- id: has_attribute
  description: connects any entity to an attribute
  display_name: has attribute
  cardinality: multi
- id: category
  display_name: named thing_category
  cardinality: multi
- id: in_taxon
  description: connects an entity to its taxonomic classification. Only certain kinds
    of entities can be taxonomically classified; see 'thing with taxon'
  display_name: in taxon
  cardinality: multi
- id: has_computational_sequence
  description: connects a service feature to its sequence of computation
  display_name: has computational sequence
- id: timepoint
  description: a point in time
  display_name: timepoint
- id: has_componentservice_or_servicetype
  description: connects an entity with one or more componentservice or servicetypes
  display_name: has componentservice or servicetype
  cardinality: multi
