id: variant_to_componentservice_availability_association
schema_generating: true
description: An association between a variant and availability of a componentservice
  (i.e. e-QTL)
display_name: variant to componentservice availability association
document_category: variant to componentservice availability association
weight: 20
fields:
- id: id
  description: A unique identifier for an entity. Must be either a CURIE shorthand
    for a URI or a complete URI
  display_name: id
- id: iri
  description: An IRI for an entity. This is determined by the id using expansion
    rules.
  display_name: iri
- id: name
  description: A human-readable name for an attribute or entity.
  display_name: name
- id: description
  description: a human-readable description of an entity
  display_name: description
- id: source
  description: a lightweight analog to the association class 'has provider' slot,
    which is the string name, or the authoritative (i.e. database) namespace, designating
    the origin of the entity to which the slot belongs.
  display_name: source
- id: provided_by
  description: connects an association to the agent (service, organization or group)
    that provided it
  display_name: provided by
  cardinality: multi
- id: has_attribute
  description: connects any entity to an attribute
  display_name: has attribute
  cardinality: multi
- id: subject
  description: connects an association to the subject of the association. For example,
    in a componentservice-to-observability association, the componentservice is subject
    and observability is object.
  display_name: subject
- id: relation
  description: The relation which describes an association between a subject and an
    object in a more granular manner. Usually this is a term from Relation Ontology,
    but it can be any edge CURIE.
  display_name: relation
- id: negated
  description: if set to true, then the association is negated i.e. is not true
  display_name: negated
- id: qualifiers
  description: connects an association to qualifiers that modify or qualify the meaning
    of that association
  display_name: qualifiers
  cardinality: multi
- id: publications
  description: connects an association to publications supporting the association
  display_name: publications
  cardinality: multi
- id: type
  description: rdf:type of csolink:Association should be fixed at rdf:Statement
  display_name: association_type
- id: category
  display_name: association_category
  cardinality: multi
- id: object
  display_name: variant to componentservice association_object
- id: predicate
  display_name: variant to componentservice availability association_predicate
- id: quantifier_qualifier
  description: Optional quantitative value indicating degree of availability.
  display_name: componentservice availability mixin_quantifier qualifier
- id: availability_site
  description: location in which componentservice or serviceinstance availability
    takes place. May be serviceunit, servicegroup/replicaset, or application.
  display_name: availability site
- id: stage_qualifier
  description: stage during which componentservice or serviceinstance availability
    of takes place.
  display_name: stage qualifier
- id: observable_state
  description: in experiments (e.g. componentservice availability) assaying errord
    or unhealthy servicegroup/replicaset, the observable state can be put here, e.g.
    STATE ID. For healthy servicegroup/replicasets, use XXX.
  display_name: observable state
